// apps/react/src/components/LoadingState.jsx
import React from 'react';

const LoadingState = ({ isVisible }) => {
  return (
    <div 
      className="loading" 
      data-testid="loading" 
      hidden={!isVisible}
    >
      <div className="loading__spinner"></div>
      <p>Loading weather data...</p>
    </div>
  );
};

export default React.memo(LoadingState);

// apps/angular/src/app/components/loading-state.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loading-state',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="loading"
      data-testid="loading"
      [hidden]="!isVisible"
    >
      <div class="loading__spinner"></div>
      <p>Loading weather data...</p>
    </div>
  `
})
export class LoadingStateComponent {
  @Input() isVisible = false;
}
