// apps/solid/src/components/Forecast.jsx
import { createSignal, Show, For } from 'solid-js';
import ForecastItem from './ForecastItem';

function Forecast(props) {
  const [activeForecastIndex, setActiveForecastIndex] = createSignal(null);

  const handleToggleForecast = (index) => {
    if (activeForecastIndex() === index) {
      setActiveForecastIndex(null);
    } else {
      setActiveForecastIndex(index);
      
      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  };

  return (
    <Show when={props.weatherData}>
      <section class="forecast-section">
        <h2 class="section-title">7-Day Forecast</h2>
        <div class="forecast">
          <div class="forecast__list" data-testid="forecast-list">
            <For each={props.weatherData.daily.time.slice(0, 7)}>
              {(date, index) => (
                <ForecastItem
                  daily={props.weatherData.daily}
                  index={index()}
                  isActive={activeForecastIndex() === index()}
                  onToggle={handleToggleForecast}
                />
              )}
            </For>
          </div>
        </div>
      </section>
    </Show>
  );
}

export default Forecast;

// apps/react/src/components/Forecast.jsx
import React, { useState, useEffect, useCallback } from 'react';
import ForecastItem from './ForecastItem';

const Forecast = ({ weatherData }) => {
  const [activeForecastIndex, setActiveForecastIndex] = useState(null);

  const handleToggleForecast = useCallback((index) => {
    setActiveForecastIndex(currentIndex => 
      currentIndex === index ? null : index
    );
  }, []);

  useEffect(() => {
    if (activeForecastIndex !== null) {
      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  }, [activeForecastIndex]);

  if (!weatherData) return null;

  const { daily } = weatherData;

  return (
    <section className="forecast-section">
      <h2 className="section-title">7-Day Forecast</h2>
      <div className="forecast">
        <div className="forecast__list" data-testid="forecast-list">
          {daily.time.map((date, index) => (
            <ForecastItem
              key={date}
              daily={daily}
              index={index}
              isActive={activeForecastIndex === index}
              onToggle={handleToggleForecast}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Forecast;
