// apps/svelte/src/lib/components/SearchForm.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte';
  import { browser } from '$app/environment';

  export let isLoading = false;

  const dispatch = createEventDispatcher();
  let inputElement;
  let inputValue = '';

  onMount(() => {
    if (browser) {
      // Set initial value from localStorage
      const savedLocation = getSavedLocation();
      if (savedLocation) {
        inputValue = savedLocation;
      } else {
        inputValue = 'London';
      }
    }
  });

  function handleSubmit() {
    const city = inputValue?.trim();
    
    if (!city) {
      return;
    }
    
    dispatch('search', city);
  }

  function getSavedLocation() {
    if (!browser) return null;
    
    try {
      return localStorage.getItem('weather-app-location');
    } catch (error) {
      console.warn('Could not load saved location:', error);
      return null;
    }
  }
</script>

<section class="search-section">
  <form class="search-form" data-testid="search-form" on:submit|preventDefault={handleSubmit}>
    <div class="search-form__group">
      <label for="location-input" class="sr-only">Enter city name</label>
      <input 
        bind:this={inputElement}
        bind:value={inputValue}
        type="text" 
        id="location-input"
        class="search-input" 
        placeholder="Enter city name..."
        data-testid="search-input"
        autocomplete="off"
      />
      <button 
        type="submit" 
        class="search-button" 
        data-testid="search-button"
        disabled={isLoading}
      >
        <span class="search-button__text">
          {isLoading ? 'Loading...' : 'Get Weather'}
        </span>
        <span class="search-button__icon">🌦️</span>
      </button>
    </div>
  </form>
</section>

// apps/react/src/components/SearchForm.jsx
import React, { useRef, useEffect, useCallback } from 'react';

const SearchForm = ({ onSearch, isLoading }) => {
  const inputRef = useRef(null);

  useEffect(() => {
    // Set initial value from localStorage
    const savedLocation = localStorage.getItem('weather-app-location');
    if (savedLocation && inputRef.current) {
      inputRef.current.value = savedLocation;
    } else if (inputRef.current) {
      inputRef.current.value = 'London';
    }
  }, []);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    const city = inputRef.current?.value?.trim();
    
    if (!city) {
      return;
    }
    
    onSearch(city);
  }, [onSearch]);

  return (
    <section className="search-section">
      <form className="search-form" data-testid="search-form" onSubmit={handleSubmit}>
        <div className="search-form__group">
          <label htmlFor="location-input" className="sr-only">Enter city name</label>
          <input 
            type="text" 
            id="location-input"
            className="search-input" 
            placeholder="Enter city name..."
            data-testid="search-input"
            autoComplete="off"
            ref={inputRef}
          />
          <button 
            type="submit" 
            className="search-button" 
            data-testid="search-button"
            disabled={isLoading}
          >
            <span className="search-button__text">
              {isLoading ? 'Loading...' : 'Get Weather'}
            </span>
            <span className="search-button__icon">🌦️</span>
          </button>
        </div>
      </form>
    </section>
  );
};

export default React.memo(SearchForm);
