// apps/qwik/src/components/SearchForm.tsx
import { component$, useSignal, $, useTask$ } from '@builder.io/qwik';

interface SearchFormProps {
  onSearch: (city: string) => void;
  isLoading?: boolean;
  currentValue?: string;
}

export const SearchForm = component$<SearchFormProps>(({ onSearch, isLoading, currentValue }) => {
  const inputValue = useSignal(currentValue || '');

  // Update input value when currentValue changes
  useTask$(({ track }) => {
    track(() => currentValue);
    if (currentValue !== undefined) {
      inputValue.value = currentValue;
    }
  });

  const handleSubmit = $((event: SubmitEvent) => {
    event.preventDefault();
    const city = inputValue.value.trim();
    if (city) {
      onSearch(city);
    }
  });

  return (
    <section class="search-section">
      <form
        class="search-form"
        data-testid="search-form"
        preventdefault:submit
        onSubmit$={handleSubmit}
      >
        <div class="search-form__group">
          <label for="location-input" class="sr-only">Enter city name</label>
          <input
            id="location-input"
            type="text"
            class="search-input"
            placeholder="Enter city name..."
            data-testid="search-input"
            data-testid="search-input"
            autocomplete="off"
            bind:value={inputValue}
            disabled={isLoading}
            tabIndex={1}
          />
          <button 
            type="submit" 
            class="search-button"
            data-testid="search-button"
            disabled={isLoading}
          >
            <span class="search-button__text">
              {isLoading ? 'Loading...' : 'Get Weather'}
            </span>
            <span class="search-button__icon">🌦️</span>
          </button>
        </div>
      </form>
    </section>
  );
});

// apps/react/src/components/SearchForm.jsx
import React, { useRef, useEffect, useCallback } from 'react';

const SearchForm = ({ onSearch, isLoading }) => {
  const inputRef = useRef(null);

  useEffect(() => {
    // Set initial value from localStorage
    const savedLocation = localStorage.getItem('weather-app-location');
    if (savedLocation && inputRef.current) {
      inputRef.current.value = savedLocation;
    } else if (inputRef.current) {
      inputRef.current.value = 'London';
    }
  }, []);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    const city = inputRef.current?.value?.trim();
    
    if (!city) {
      return;
    }
    
    onSearch(city);
  }, [onSearch]);

  return (
    <section className="search-section">
      <form className="search-form" data-testid="search-form" onSubmit={handleSubmit}>
        <div className="search-form__group">
          <label htmlFor="location-input" className="sr-only">Enter city name</label>
          <input 
            type="text" 
            id="location-input"
            className="search-input" 
            placeholder="Enter city name..."
            data-testid="search-input"
            autoComplete="off"
            ref={inputRef}
          />
          <button 
            type="submit" 
            className="search-button" 
            data-testid="search-button"
            disabled={isLoading}
          >
            <span className="search-button__text">
              {isLoading ? 'Loading...' : 'Get Weather'}
            </span>
            <span className="search-button__icon">🌦️</span>
          </button>
        </div>
      </form>
    </section>
  );
};

export default React.memo(SearchForm);
