// apps/preact/src/components/Forecast.jsx
import { useState, useEffect } from 'preact/hooks';
import ForecastItem from './ForecastItem';

const Forecast = ({ weatherData = null }) => {
  const [activeForecastIndex, setActiveForecastIndex] = useState(null);

  const handleToggleForecast = (index) => {
    if (activeForecastIndex === index) {
      setActiveForecastIndex(null);
    } else {
      setActiveForecastIndex(index);
      
      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  };

  if (!weatherData) return null;

  return (
    <section class="forecast-section">
      <h2 class="section-title">7-Day Forecast</h2>
      <div class="forecast">
        <div class="forecast__list" data-testid="forecast-list">
          {weatherData.daily.time.slice(0, 7).map((date, index) => (
            <ForecastItem
              key={index}
              daily={weatherData.daily}
              index={index}
              isActive={activeForecastIndex === index}
              onToggle={handleToggleForecast}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Forecast;

// apps/solid/src/components/Forecast.jsx
import { createSignal, Show, For } from 'solid-js';
import ForecastItem from './ForecastItem';

function Forecast(props) {
  const [activeForecastIndex, setActiveForecastIndex] = createSignal(null);

  const handleToggleForecast = (index) => {
    if (activeForecastIndex() === index) {
      setActiveForecastIndex(null);
    } else {
      setActiveForecastIndex(index);
      
      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  };

  return (
    <Show when={props.weatherData}>
      <section class="forecast-section">
        <h2 class="section-title">7-Day Forecast</h2>
        <div class="forecast">
          <div class="forecast__list" data-testid="forecast-list">
            <For each={props.weatherData.daily.time.slice(0, 7)}>
              {(date, index) => (
                <ForecastItem
                  daily={props.weatherData.daily}
                  index={index()}
                  isActive={activeForecastIndex() === index()}
                  onToggle={handleToggleForecast}
                />
              )}
            </For>
          </div>
        </div>
      </section>
    </Show>
  );
}

export default Forecast;
