// apps/solid/src/App.jsx
import { onMount, createEffect } from 'solid-js';
import { weatherStore } from './stores/weatherStore';
import SearchForm from './components/SearchForm';
import LoadingState from './components/LoadingState';
import ErrorState from './components/ErrorState';
import WeatherContent from './components/WeatherContent';

function App() {
  // Initialize the weather store when the component mounts
  onMount(() => {
    weatherStore.initialize();
  });

  const handleSearch = async (city) => {
    await weatherStore.loadWeather(city);
  };

  return (
    <div>
      <header class="header">
        <div class="container">
          <h1 class="header__title">Weather Front</h1>
        </div>
      </header>

      <main class="main">
        <div class="container">
          <SearchForm 
            isLoading={weatherStore.isLoadingSignal()}
            currentLocation={weatherStore.weatherDataSignal()?.locationName}
            onSearch={handleSearch}
          />

          <div class="weather-container" data-testid="weather-container">
            <LoadingState isVisible={weatherStore.isLoadingSignal()} />
            
            <ErrorState 
              isVisible={!!weatherStore.errorSignal() && !weatherStore.isLoadingSignal()}
              message={weatherStore.errorSignal()}
            />
            
            <WeatherContent 
              isVisible={!!weatherStore.weatherDataSignal() && !weatherStore.isLoadingSignal() && !weatherStore.errorSignal()}
              weatherData={weatherStore.weatherDataSignal()}
            />
          </div>
        </div>
      </main>

      <footer class="footer">
        <div class="container">
          <p class="footer__text">
            Built with Solid.js • MIT License • 
            <a href="https://github.com/Lissy93" class="footer__link" target="_blank" rel="noopener">
              Alicia Sykes
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}

export default App;

// apps/react/src/App.jsx
import React from 'react';
import ErrorBoundary from './components/ErrorBoundary';
import SearchForm from './components/SearchForm';
import LoadingState from './components/LoadingState';
import ErrorState from './components/ErrorState';
import WeatherContent from './components/WeatherContent';
import useWeatherData from './hooks/useWeatherData';

function App() {
  const { weatherData, isLoading, error, loadWeather } = useWeatherData();

  const handleSearch = async (city) => {
    await loadWeather(city);
  };

  return (
    <ErrorBoundary>
      <header className="header">
        <div className="container">
          <h1 className="header__title">Weather Front</h1>
        </div>
      </header>

      <main className="main">
        <div className="container">
          <SearchForm 
            onSearch={handleSearch} 
            isLoading={isLoading}
          />

          <div className="weather-container" data-testid="weather-container">
            <LoadingState isVisible={isLoading} />
            <ErrorState isVisible={!!error && !isLoading} message={error} />
            <WeatherContent isVisible={!!weatherData && !isLoading && !error} weatherData={weatherData} />
          </div>
        </div>
      </main>

      <footer className="footer">
        <div className="container">
          <p className="footer__text">
            Built with React • MIT License • 
            <a href="https://github.com/Lissy93" className="footer__link" target="_blank" rel="noopener">
              Alicia Sykes
            </a>
          </p>
        </div>
      </footer>
    </ErrorBoundary>
  );
}

export default App;
