// apps/solid/src/components/SearchForm.jsx
import { createSignal, onMount, createEffect } from 'solid-js';

function SearchForm(props) {
  const [inputValue, setInputValue] = createSignal('');
  const [hasInitialized, setHasInitialized] = createSignal(false);

  onMount(() => {
    // Set initial value from localStorage
    const savedLocation = getSavedLocation();
    if (savedLocation) {
      setInputValue(savedLocation);
      setHasInitialized(true);
    }
  });

  // Only update input value from currentLocation on initial load if no saved location exists
  createEffect(() => {
    if (props.currentLocation && !inputValue() && !hasInitialized()) {
      setInputValue(props.currentLocation);
    }
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    const city = inputValue()?.trim();
    
    if (!city) {
      return;
    }
    
    props.onSearch?.(city);
  };

  return (
    <section class="search-section">
      <form class="search-form" data-testid="search-form" onSubmit={handleSubmit}>
        <div class="search-form__group">
          <label for="location-input" class="sr-only">Enter city name</label>
          <input 
            value={inputValue()}
            onInput={(e) => setInputValue(e.target.value)}
            type="text" 
            id="location-input"
            class="search-input" 
            placeholder="Enter city name..."
            data-testid="search-input"
            autocomplete="off"
          />
          <button 
            type="submit" 
            class="search-button" 
            data-testid="search-button"
            disabled={props.isLoading}
          >
            <span class="search-button__text">
              {props.isLoading ? 'Loading...' : 'Get Weather'}
            </span>
            <span class="search-button__icon">🌦️</span>
          </button>
        </div>
      </form>
    </section>
  );
}

function getSavedLocation() {
  try {
    return localStorage.getItem('weather-app-location');
  } catch (error) {
    console.warn('Could not load saved location:', error);
    return null;
  }
}

export default SearchForm;

// apps/svelte/src/lib/components/SearchForm.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte';
  import { browser } from '$app/environment';

  export let isLoading = false;

  const dispatch = createEventDispatcher();
  let inputElement;
  let inputValue = '';

  onMount(() => {
    if (browser) {
      // Set initial value from localStorage
      const savedLocation = getSavedLocation();
      if (savedLocation) {
        inputValue = savedLocation;
      } else {
        inputValue = 'London';
      }
    }
  });

  function handleSubmit() {
    const city = inputValue?.trim();
    
    if (!city) {
      return;
    }
    
    dispatch('search', city);
  }

  function getSavedLocation() {
    if (!browser) return null;
    
    try {
      return localStorage.getItem('weather-app-location');
    } catch (error) {
      console.warn('Could not load saved location:', error);
      return null;
    }
  }
</script>

<section class="search-section">
  <form class="search-form" data-testid="search-form" on:submit|preventDefault={handleSubmit}>
    <div class="search-form__group">
      <label for="location-input" class="sr-only">Enter city name</label>
      <input 
        bind:this={inputElement}
        bind:value={inputValue}
        type="text" 
        id="location-input"
        class="search-input" 
        placeholder="Enter city name..."
        data-testid="search-input"
        autocomplete="off"
      />
      <button 
        type="submit" 
        class="search-button" 
        data-testid="search-button"
        disabled={isLoading}
      >
        <span class="search-button__text">
          {isLoading ? 'Loading...' : 'Get Weather'}
        </span>
        <span class="search-button__icon">🌦️</span>
      </button>
    </div>
  </form>
</section>
