// apps/angular/src/app/components/forecast.component.ts
import { Component, ElementRef, Injector, afterNextRender, inject, input, signal } from '@angular/core';
import type { WeatherData } from '../types/weather.types';
import { ForecastItemComponent } from './forecast-item.component';

@Component({
  selector: 'app-forecast',
  imports: [ForecastItemComponent],
  template: `
    @if (weatherData(); as weatherData) {
      <section class="forecast-section">
      <h2 class="section-title">7-Day Forecast</h2>
      <div class="forecast">
        <div class="forecast__list" data-testid="forecast-list">
          @for (date of weatherData.daily.time; track date; let i = $index) {
          <app-forecast-item
            [daily]="weatherData.daily"
            [index]="i"
            [isActive]="activeForecastIndex() === i"
            (toggle)="onToggleForecast($event)"
          ></app-forecast-item>
          }
        </div>
      </div>
      </section>
    }
  `
})
export class ForecastComponent {
  private readonly elementRef = inject(ElementRef<HTMLElement>);
  private readonly injector = inject(Injector);

  readonly weatherData = input<WeatherData | null | undefined>(null);
  readonly activeForecastIndex = signal<number | null>(null);

  onToggleForecast(index: number): void {
    if (this.activeForecastIndex() === index) {
      this.activeForecastIndex.set(null);
    } else {
      this.activeForecastIndex.set(index);
      afterNextRender(() => {
        const activeElement = (this.elementRef.nativeElement as HTMLElement).querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, { injector: this.injector });
    }
  }
}

// apps/octane/src/components/Forecast.tsx
import { useState, useEffect, useCallback } from 'octane';
import ForecastItem from './ForecastItem.tsx';

const Forecast = ({ weatherData }) => {
  const [activeForecastIndex, setActiveForecastIndex] = useState(null);

  const handleToggleForecast = useCallback((index) => {
    setActiveForecastIndex(currentIndex =>
      currentIndex === index ? null : index
    );
  }, []);

  useEffect(() => {
    if (activeForecastIndex !== null) {
      // Smooth scroll to the expanded item
      setTimeout(() => {
        const activeElement = document.querySelector('.forecast-item.active');
        if (activeElement) {
          activeElement.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      }, 100);
    }
  }, [activeForecastIndex]);

  if (!weatherData) {return null;}

  const { daily } = weatherData;

  return (
    <section className="forecast-section">
      <h2 className="section-title">7-Day Forecast</h2>
      <div className="forecast">
        <div className="forecast__list" data-testid="forecast-list">
          {daily.time.map((date, index) => (
            <ForecastItem
              key={date}
              daily={daily}
              index={index}
              isActive={activeForecastIndex === index}
              onToggle={handleToggleForecast}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

export default Forecast;
