// apps/react/src/components/WeatherContent.jsx
import React from 'react';
import CurrentWeather from './CurrentWeather';
import Forecast from './Forecast';

const WeatherContent = ({ isVisible, weatherData }) => {
  return (
    <div 
      className="weather-content" 
      data-testid="weather-content" 
      hidden={!isVisible}
    >
      <div className="weather-layout">
        <CurrentWeather weatherData={weatherData} />
        <Forecast weatherData={weatherData} />
      </div>
    </div>
  );
};

export default React.memo(WeatherContent);

// apps/qwik/src/components/WeatherContent.tsx
import { component$ } from '@builder.io/qwik';
import type { WeatherData } from '../services/WeatherService';
import { CurrentWeather } from './CurrentWeather';
import { Forecast } from './Forecast';

interface WeatherContentProps {
  weatherData: WeatherData;
}

export const WeatherContent = component$<WeatherContentProps>(({ weatherData }) => {
  return (
    <div class="weather-content" data-testid="weather-content">
      <div class="weather-layout">
        <CurrentWeather weatherData={weatherData} />
        <Forecast weatherData={weatherData} />
      </div>
    </div>
  );
});
