// apps/octane/src/components/ForecastItem.tsx
import { memo, useCallback, useMemo } from 'octane';
import WeatherUtils from '../utils/WeatherUtils.js';

const ForecastItem = ({ daily, index, isActive, onToggle }) => {
  const forecastData = useMemo(() => ({
    dayName: WeatherUtils.formatDate(daily.time[index]),
    weatherCode: daily.weather_code[index],
    high: daily.temperature_2m_max[index],
    low: daily.temperature_2m_min[index]
  }), [daily, index]);

  const condition = useMemo(() =>
    WeatherUtils.getWeatherDescription(forecastData.weatherCode),
  [forecastData.weatherCode]
  );

  const icon = useMemo(() =>
    WeatherUtils.getWeatherIcon(forecastData.weatherCode),
  [forecastData.weatherCode]
  );

  const handleClick = useCallback(() => {
    onToggle(index);
  }, [onToggle, index]);

  const handleKeyDown = useCallback((e) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onToggle(index);
    }
  }, [onToggle, index]);

  return (
    <div
      className={`forecast-item ${isActive ? 'active' : ''}`}
      data-testid="forecast-item"
      tabIndex="0"
      role="button"
      aria-label={`View detailed forecast for ${forecastData.dayName}`}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      <div className="forecast-item__day">{forecastData.dayName}</div>
      <div className="forecast-item__icon">{icon}</div>
      <div className="forecast-item__info">
        <div className="forecast-item__condition">{condition}</div>
        <div className="forecast-item__temps" data-testid="forecast-temps">
          <span className="forecast-item__high" data-testid="forecast-high">
            {WeatherUtils.formatTemperature(forecastData.high)}
          </span>
          <span className="forecast-item__low" data-testid="forecast-low">
            {WeatherUtils.formatTemperature(forecastData.low)}
          </span>
        </div>
      </div>

      {isActive && (
        <div className="forecast-item__details">
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">Sunrise</div>
            <div className="forecast-detail-item__value">
              {WeatherUtils.formatTime(daily.sunrise[index])}
            </div>
          </div>
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">Sunset</div>
            <div className="forecast-detail-item__value">
              {WeatherUtils.formatTime(daily.sunset[index])}
            </div>
          </div>
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">Rain</div>
            <div className="forecast-detail-item__value">
              {daily.rain_sum[index].toFixed(1)} mm
            </div>
          </div>
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">UV Index</div>
            <div className="forecast-detail-item__value">
              {daily.uv_index_max[index].toFixed(1)}
            </div>
          </div>
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">Precipitation</div>
            <div className="forecast-detail-item__value">
              {WeatherUtils.formatPercentage(daily.precipitation_probability_max[index])}
            </div>
          </div>
          <div className="forecast-detail-item">
            <div className="forecast-detail-item__label">Temperature</div>
            <div className="forecast-detail-item__value">
              {WeatherUtils.formatTemperature(daily.temperature_2m_min[index])} to {WeatherUtils.formatTemperature(daily.temperature_2m_max[index])}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default memo(ForecastItem);

// apps/vue-vapor/src/components/ForecastItem.vue
<template>
  <div
    class="forecast-item"
    :class="{ active: isActive }"
    data-testid="forecast-item"
    @click="$emit('click')"
    tabindex="0"
    @keydown.enter="$emit('click')"
    @keydown.space.prevent="$emit('click')"
  >
    <div class="forecast-item__day">{{ dayName }}</div>
    <div class="forecast-item__icon">{{ icon }}</div>
    <div class="forecast-item__info">
      <div class="forecast-item__condition">{{ condition }}</div>
      <div class="forecast-item__temps" data-testid="forecast-temps">
        <span class="forecast-item__high" data-testid="forecast-high">
          {{ WeatherUtils.formatTemperature(forecastData.high) }}
        </span>
        <span class="forecast-item__low" data-testid="forecast-low">
          {{ WeatherUtils.formatTemperature(forecastData.low) }}
        </span>
      </div>
    </div>

    <div v-if="isActive" class="forecast-item__details">
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">Sunrise</div>
        <div class="forecast-detail-item__value">{{ WeatherUtils.formatTime(forecastData.sunrise) }}</div>
      </div>
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">Sunset</div>
        <div class="forecast-detail-item__value">{{ WeatherUtils.formatTime(forecastData.sunset) }}</div>
      </div>
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">Rain</div>
        <div class="forecast-detail-item__value">{{ forecastData.rainSum.toFixed(1) }} mm</div>
      </div>
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">UV Index</div>
        <div class="forecast-detail-item__value">{{ forecastData.uvIndex.toFixed(1) }}</div>
      </div>
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">Precipitation</div>
        <div class="forecast-detail-item__value">{{ WeatherUtils.formatPercentage(forecastData.precipitationProb) }}</div>
      </div>
      <div class="forecast-detail-item">
        <div class="forecast-detail-item__label">Temperature</div>
        <div class="forecast-detail-item__value">
          {{ WeatherUtils.formatTemperature(forecastData.high) }} / {{ WeatherUtils.formatTemperature(forecastData.low) }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup vapor>
import { computed } from 'vue'
import { WeatherUtils } from '../utils/weatherUtils.js'

const props = defineProps({
  forecastData: {
    type: Object,
    required: true
  },
  isActive: {
    type: Boolean,
    default: false
  }
})

defineEmits(['click'])

const dayName = computed(() => {
  return WeatherUtils.formatDate(props.forecastData.date)
})

const icon = computed(() => {
  return WeatherUtils.getWeatherIcon(props.forecastData.weatherCode, 1)
})

const condition = computed(() => {
  return WeatherUtils.getWeatherDescription(props.forecastData.weatherCode)
})
</script>
