// apps/octane/src/components/SearchForm.tsx
import { memo, useCallback, useEffect, useRef } from 'octane';

const SearchForm = ({ onSearch, isLoading }) => {
  const inputRef = useRef(null);

  useEffect(() => {
    // Set initial value from localStorage
    const savedLocation = localStorage.getItem('weather-app-location');
    if (savedLocation && inputRef.current) {
      inputRef.current.value = savedLocation;
    } else if (inputRef.current) {
      inputRef.current.value = 'London';
    }
  }, []);

  const handleSubmit = useCallback((e) => {
    e.preventDefault();
    const city = inputRef.current?.value?.trim();

    if (!city) {
      return;
    }

    onSearch(city);
  }, [onSearch]);

  return (
    <section className="search-section">
      <form className="search-form" data-testid="search-form" onSubmit={handleSubmit}>
        <div className="search-form__group">
          <label htmlFor="location-input" className="sr-only">Enter city name</label>
          <input
            type="text"
            id="location-input"
            className="search-input"
            placeholder="Enter city name..."
            data-testid="search-input"
            autoComplete="off"
            ref={inputRef}
          />
          <button
            type="submit"
            className="search-button"
            data-testid="search-button"
            disabled={isLoading}
          >
            <span className="search-button__text">
              {isLoading ? 'Loading...' : 'Get Weather'}
            </span>
            <span className="search-button__icon">🌦️</span>
          </button>
        </div>
      </form>
    </section>
  );
};

export default memo(SearchForm);

// apps/vue-vapor/src/components/SearchForm.vue
<template>
  <section class="search-section">
    <form
      class="search-form"
      data-testid="search-form"
      @submit="handleSubmit"
    >
      <div class="search-form__group">
        <label for="location-input" class="sr-only">Enter city name</label>
        <input
          id="location-input"
          v-model="inputValue"
          type="text"
          class="search-input"
          placeholder="Enter city name..."
          data-testid="search-input"
          autocomplete="off"
          :disabled="isLoading"
        />
        <button
          type="submit"
          class="search-button"
          data-testid="search-button"
          :disabled="isLoading"
        >
          <span class="search-button__text">
            {{ isLoading ? 'Loading...' : 'Get Weather' }}
          </span>
          <span class="search-button__icon">🌦️</span>
        </button>
      </div>
    </form>
  </section>
</template>

<script setup vapor>
import { ref, watch } from 'vue'

const props = defineProps({
  isLoading: {
    type: Boolean,
    default: false
  },
  currentValue: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['search'])

const inputValue = ref(props.currentValue)

// Watch for changes in currentValue prop
watch(() => props.currentValue, (newValue) => {
  inputValue.value = newValue
}, { immediate: true })

const handleSubmit = (event) => {
  event.preventDefault()
  const city = inputValue.value.trim()
  if (city) {
    emit('search', city)
  }
}
</script>
