// apps/octane/src/components/WeatherContent.tsx
import { memo } from 'octane';
import CurrentWeather from './CurrentWeather.tsx';
import Forecast from './Forecast.tsx';

const WeatherContent = ({ isVisible, weatherData }) => {
  return (
    <div
      className="weather-content"
      data-testid="weather-content"
      hidden={!isVisible}
    >
      <div className="weather-layout">
        <CurrentWeather weatherData={weatherData} />
        <Forecast weatherData={weatherData} />
      </div>
    </div>
  );
};

export default memo(WeatherContent);

// apps/vue-vapor/src/components/WeatherContent.vue
<template>
  <div class="weather-content" data-testid="weather-content">
    <div class="weather-layout">
      <CurrentWeather :weather-data="weatherData" />
      <Forecast :weather-data="weatherData" />
    </div>
  </div>
</template>

<script setup vapor>
import CurrentWeather from './CurrentWeather.vue'
import Forecast from './Forecast.vue'

defineProps({
  weatherData: {
    type: Object,
    required: true
  }
})
</script>
