// apps/angular/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { WeatherStateService } from './services/weather-state.service';
import { SearchFormComponent } from './components/search-form.component';
import { LoadingStateComponent } from './components/loading-state.component';
import { ErrorStateComponent } from './components/error-state.component';
import { WeatherContentComponent } from './components/weather-content.component';

@Component({
  selector: 'app-root',
  imports: [
    SearchFormComponent,
    LoadingStateComponent,
    ErrorStateComponent,
    WeatherContentComponent
  ],
  template: `
    <header class="header">
      <div class="container">
        <h1 class="header__title">Weather Front</h1>
      </div>
    </header>

    <main class="main">
      <div class="container">
        <app-search-form
          [isLoading]="weatherState.weather.isLoading()"
          (search)="weatherState.loadWeather($event)"
        ></app-search-form>

        <div class="weather-container" data-testid="weather-container">
          <app-loading-state [isVisible]="weatherState.weather.isLoading()"></app-loading-state>

          <app-error-state
            [isVisible]="!!weatherState.weather.error() && !weatherState.weather.isLoading()"
            [message]="$any(weatherState.weather.error())?.message"
          ></app-error-state>

          @if (weatherState.weather.hasValue() && !weatherState.weather.isLoading() && !weatherState.weather.error()) {
            <app-weather-content
              [weatherData]="weatherState.weather.value()!"
            ></app-weather-content>
          }
        </div>
      </div>
    </main>

    <footer class="footer">
      <div class="container">
        <p class="footer__text">
          Built with Angular • MIT License •
          <a href="https://github.com/Lissy93" class="footer__link" target="_blank" rel="noopener">
            Alicia Sykes
          </a>
        </p>
      </div>
    </footer>
  `
})
export class AppComponent {
  protected readonly weatherState = inject(WeatherStateService);
}

// apps/vue-vapor/src/App.vue
<template>
  <header class="header">
    <div class="container">
      <h1 class="header__title">Weather Front</h1>
    </div>
  </header>

  <main class="main">
    <div class="container">
      <SearchForm
        @search="searchWeather"
        :is-loading="isLoading"
        :current-value="searchValue"
      />

      <div class="weather-container" data-testid="weather-container">
        <LoadingState v-if="isLoading" />

        <ErrorState
          v-if="error && !isLoading"
          :message="error"
        />

        <WeatherContent
          v-if="weatherData && !isLoading && !error"
          :weather-data="weatherData"
        />
      </div>
    </div>
  </main>

  <footer class="footer">
    <div class="container">
      <p class="footer__text">
        Built with Vue Vapor Mode • MIT License •
        <a href="https://github.com/Lissy93" class="footer__link" target="_blank" rel="noopener">Alicia Sykes</a>
      </p>
    </div>
  </footer>
</template>

<script setup vapor>
import { ref, onMounted } from 'vue'
import SearchForm from './components/SearchForm.vue'
import LoadingState from './components/LoadingState.vue'
import ErrorState from './components/ErrorState.vue'
import WeatherContent from './components/WeatherContent.vue'
import { weatherService } from './services/weatherService.js'

const weatherData = ref(null)
const isLoading = ref(false)
const error = ref(null)
const searchValue = ref('London')

const searchWeather = async (city) => {
  isLoading.value = true
  error.value = null

  try {
    const data = await weatherService.getWeatherByCity(city)
    weatherData.value = data
    searchValue.value = city

    // Save to localStorage
    try {
      localStorage.setItem('weather-app-location', city)
    } catch (e) {
      // Ignore localStorage errors
    }
  } catch (err) {
    error.value = err.message || 'Failed to fetch weather data'
    weatherData.value = null
  } finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  let initialCity = 'London'

  // Try to get saved location from localStorage
  try {
    const savedLocation = localStorage.getItem('weather-app-location')
    if (savedLocation) {
      initialCity = savedLocation
    }
  } catch (e) {
    // Ignore localStorage errors
  }

  await searchWeather(initialCity)
})
</script>
